/**
 * This class is generated by jOOQ
 */
package Jooq;


import Jooq.information_schema.InformationSchema;
import Jooq.pg_catalog.PgCatalog;
import Jooq.pg_temp_1.PgTemp_1;
import Jooq.pg_toast.PgToast;
import Jooq.pg_toast_temp_1.PgToastTemp_1;
import Jooq.public_.Public;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1069248370;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>pg_toast</code>.
     */
    public final PgToast PG_TOAST = Jooq.pg_toast.PgToast.PG_TOAST;

    /**
     * The schema <code>pg_temp_1</code>.
     */
    public final PgTemp_1 PG_TEMP_1 = Jooq.pg_temp_1.PgTemp_1.PG_TEMP_1;

    /**
     * The schema <code>pg_toast_temp_1</code>.
     */
    public final PgToastTemp_1 PG_TOAST_TEMP_1 = Jooq.pg_toast_temp_1.PgToastTemp_1.PG_TOAST_TEMP_1;

    /**
     * The schema <code>pg_catalog</code>.
     */
    public final PgCatalog PG_CATALOG = Jooq.pg_catalog.PgCatalog.PG_CATALOG;

    /**
     * The schema <code>public</code>.
     */
    public final Public PUBLIC = Jooq.public_.Public.PUBLIC;

    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = Jooq.information_schema.InformationSchema.INFORMATION_SCHEMA;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            PgToast.PG_TOAST,
            PgTemp_1.PG_TEMP_1,
            PgToastTemp_1.PG_TOAST_TEMP_1,
            PgCatalog.PG_CATALOG,
            Public.PUBLIC,
            InformationSchema.INFORMATION_SCHEMA);
    }
}
