/**
 * This class is generated by jOOQ
 */
package Jooq.public_.tables.records;


import Jooq.public_.tables.Employee;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends TableRecordImpl<EmployeeRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1264975432;

    /**
     * Setter for <code>public.EMPLOYEE.User</code>.
     */
    public void setUser(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.EMPLOYEE.User</code>.
     */
    public String getUser() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.EMPLOYEE.Pass</code>.
     */
    public void setPass(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.EMPLOYEE.Pass</code>.
     */
    public String getPass() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Employee.EMPLOYEE.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employee.EMPLOYEE.PASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value1(String value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord value2(String value) {
        setPass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(String user, String pass) {
        super(Employee.EMPLOYEE);

        set(0, user);
        set(1, pass);
    }
}
