/**
 * This class is generated by jOOQ
 */
package Jooq.pg_toast;


import Jooq.DefaultCatalog;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgToast extends SchemaImpl {

    private static final long serialVersionUID = -1173064161;

    /**
     * The reference instance of <code>pg_toast</code>
     */
    public static final PgToast PG_TOAST = new PgToast();

    /**
     * No further instances allowed
     */
    private PgToast() {
        super("pg_toast", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
