/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgAm;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAmRecord extends TableRecordImpl<PgAmRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = -955920955;

    /**
     * Setter for <code>pg_catalog.pg_am.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amname</code>.
     */
    public void setAmname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amname</code>.
     */
    public String getAmname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amhandler</code>.
     */
    public void setAmhandler(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amhandler</code>.
     */
    public String getAmhandler() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_am.amtype</code>.
     */
    public void setAmtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_am.amtype</code>.
     */
    public String getAmtype() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgAm.PG_AM.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgAm.PG_AM.AMNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgAm.PG_AM.AMHANDLER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgAm.PG_AM.AMTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAmname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAmhandler();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAmtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmRecord value2(String value) {
        setAmname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmRecord value3(String value) {
        setAmhandler(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmRecord value4(String value) {
        setAmtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAmRecord
     */
    public PgAmRecord() {
        super(PgAm.PG_AM);
    }

    /**
     * Create a detached, initialised PgAmRecord
     */
    public PgAmRecord(Long oid, String amname, String amhandler, String amtype) {
        super(PgAm.PG_AM);

        set(0, oid);
        set(1, amname);
        set(2, amhandler);
        set(3, amtype);
    }
}
