/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgAmproc;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAmprocRecord extends TableRecordImpl<PgAmprocRecord> implements Record6<Long, Long, Long, Long, Short, String> {

    private static final long serialVersionUID = -1812374284;

    /**
     * Setter for <code>pg_catalog.pg_amproc.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_amproc.amprocfamily</code>.
     */
    public void setAmprocfamily(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.amprocfamily</code>.
     */
    public Long getAmprocfamily() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_amproc.amproclefttype</code>.
     */
    public void setAmproclefttype(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.amproclefttype</code>.
     */
    public Long getAmproclefttype() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_amproc.amprocrighttype</code>.
     */
    public void setAmprocrighttype(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.amprocrighttype</code>.
     */
    public Long getAmprocrighttype() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_amproc.amprocnum</code>.
     */
    public void setAmprocnum(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.amprocnum</code>.
     */
    public Short getAmprocnum() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_amproc.amproc</code>.
     */
    public void setAmproc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amproc.amproc</code>.
     */
    public String getAmproc() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Long, Short, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Long, Short, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgAmproc.PG_AMPROC.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgAmproc.PG_AMPROC.AMPROCFAMILY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgAmproc.PG_AMPROC.AMPROCLEFTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgAmproc.PG_AMPROC.AMPROCRIGHTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return PgAmproc.PG_AMPROC.AMPROCNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgAmproc.PG_AMPROC.AMPROC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAmprocfamily();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAmproclefttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getAmprocrighttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getAmprocnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAmproc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value2(Long value) {
        setAmprocfamily(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value3(Long value) {
        setAmproclefttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value4(Long value) {
        setAmprocrighttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value5(Short value) {
        setAmprocnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord value6(String value) {
        setAmproc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAmprocRecord values(Long value1, Long value2, Long value3, Long value4, Short value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAmprocRecord
     */
    public PgAmprocRecord() {
        super(PgAmproc.PG_AMPROC);
    }

    /**
     * Create a detached, initialised PgAmprocRecord
     */
    public PgAmprocRecord(Long oid, Long amprocfamily, Long amproclefttype, Long amprocrighttype, Short amprocnum, String amproc) {
        super(PgAmproc.PG_AMPROC);

        set(0, oid);
        set(1, amprocfamily);
        set(2, amproclefttype);
        set(3, amprocrighttype);
        set(4, amprocnum);
        set(5, amproc);
    }
}
