/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgAttrdef;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAttrdefRecord extends TableRecordImpl<PgAttrdefRecord> implements Record4<Long, Long, Short, Object> {

    private static final long serialVersionUID = 1697474694;

    /**
     * Setter for <code>pg_catalog.pg_attrdef.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_attrdef.adrelid</code>.
     */
    public void setAdrelid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.adrelid</code>.
     */
    public Long getAdrelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_attrdef.adnum</code>.
     */
    public void setAdnum(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.adnum</code>.
     */
    public Short getAdnum() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_attrdef.adbin</code>.
     */
    public void setAdbin(Object value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.adbin</code>.
     */
    public Object getAdbin() {
        return (Object) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Short, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Short, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgAttrdef.PG_ATTRDEF.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgAttrdef.PG_ATTRDEF.ADRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return PgAttrdef.PG_ATTRDEF.ADNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field4() {
        return PgAttrdef.PG_ATTRDEF.ADBIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAdrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getAdnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value4() {
        return getAdbin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAttrdefRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAttrdefRecord value2(Long value) {
        setAdrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAttrdefRecord value3(Short value) {
        setAdnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAttrdefRecord value4(Object value) {
        setAdbin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgAttrdefRecord values(Long value1, Long value2, Short value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAttrdefRecord
     */
    public PgAttrdefRecord() {
        super(PgAttrdef.PG_ATTRDEF);
    }

    /**
     * Create a detached, initialised PgAttrdefRecord
     */
    public PgAttrdefRecord(Long oid, Long adrelid, Short adnum, Object adbin) {
        super(PgAttrdef.PG_ATTRDEF);

        set(0, oid);
        set(1, adrelid);
        set(2, adnum);
        set(3, adbin);
    }
}
