/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgConversion;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgConversionRecord extends TableRecordImpl<PgConversionRecord> implements Record8<Long, String, Long, Long, Integer, Integer, String, Boolean> {

    private static final long serialVersionUID = 1052570947;

    /**
     * Setter for <code>pg_catalog.pg_conversion.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.conname</code>.
     */
    public void setConname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.conname</code>.
     */
    public String getConname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.connamespace</code>.
     */
    public void setConnamespace(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.connamespace</code>.
     */
    public Long getConnamespace() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.conowner</code>.
     */
    public void setConowner(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.conowner</code>.
     */
    public Long getConowner() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.conforencoding</code>.
     */
    public void setConforencoding(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.conforencoding</code>.
     */
    public Integer getConforencoding() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.contoencoding</code>.
     */
    public void setContoencoding(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.contoencoding</code>.
     */
    public Integer getContoencoding() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.conproc</code>.
     */
    public void setConproc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.conproc</code>.
     */
    public String getConproc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_conversion.condefault</code>.
     */
    public void setCondefault(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_conversion.condefault</code>.
     */
    public Boolean getCondefault() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Long, Integer, Integer, String, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Long, Integer, Integer, String, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgConversion.PG_CONVERSION.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgConversion.PG_CONVERSION.CONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgConversion.PG_CONVERSION.CONNAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgConversion.PG_CONVERSION.CONOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PgConversion.PG_CONVERSION.CONFORENCODING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PgConversion.PG_CONVERSION.CONTOENCODING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PgConversion.PG_CONVERSION.CONPROC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return PgConversion.PG_CONVERSION.CONDEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getConname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getConnamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getConowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getConforencoding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getContoencoding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getConproc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getCondefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value2(String value) {
        setConname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value3(Long value) {
        setConnamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value4(Long value) {
        setConowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value5(Integer value) {
        setConforencoding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value6(Integer value) {
        setContoencoding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value7(String value) {
        setConproc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord value8(Boolean value) {
        setCondefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgConversionRecord values(Long value1, String value2, Long value3, Long value4, Integer value5, Integer value6, String value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgConversionRecord
     */
    public PgConversionRecord() {
        super(PgConversion.PG_CONVERSION);
    }

    /**
     * Create a detached, initialised PgConversionRecord
     */
    public PgConversionRecord(Long oid, String conname, Long connamespace, Long conowner, Integer conforencoding, Integer contoencoding, String conproc, Boolean condefault) {
        super(PgConversion.PG_CONVERSION);

        set(0, oid);
        set(1, conname);
        set(2, connamespace);
        set(3, conowner);
        set(4, conforencoding);
        set(5, contoencoding);
        set(6, conproc);
        set(7, condefault);
    }
}
