/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgDefaultAcl;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDefaultAclRecord extends TableRecordImpl<PgDefaultAclRecord> implements Record5<Long, Long, Long, String, String[]> {

    private static final long serialVersionUID = -574291499;

    /**
     * Setter for <code>pg_catalog.pg_default_acl.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclrole</code>.
     */
    public void setDefaclrole(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclrole</code>.
     */
    public Long getDefaclrole() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclnamespace</code>.
     */
    public void setDefaclnamespace(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclnamespace</code>.
     */
    public Long getDefaclnamespace() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclobjtype</code>.
     */
    public void setDefaclobjtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclobjtype</code>.
     */
    public String getDefaclobjtype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_default_acl.defaclacl</code>.
     */
    public void setDefaclacl(String[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_default_acl.defaclacl</code>.
     */
    public String[] getDefaclacl() {
        return (String[]) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, String, String[]> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, String, String[]> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgDefaultAcl.PG_DEFAULT_ACL.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgDefaultAcl.PG_DEFAULT_ACL.DEFACLROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgDefaultAcl.PG_DEFAULT_ACL.DEFACLNAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgDefaultAcl.PG_DEFAULT_ACL.DEFACLOBJTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field5() {
        return PgDefaultAcl.PG_DEFAULT_ACL.DEFACLACL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDefaclrole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getDefaclnamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDefaclobjtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value5() {
        return getDefaclacl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord value2(Long value) {
        setDefaclrole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord value3(Long value) {
        setDefaclnamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord value4(String value) {
        setDefaclobjtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord value5(String[] value) {
        setDefaclacl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgDefaultAclRecord values(Long value1, Long value2, Long value3, String value4, String[] value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgDefaultAclRecord
     */
    public PgDefaultAclRecord() {
        super(PgDefaultAcl.PG_DEFAULT_ACL);
    }

    /**
     * Create a detached, initialised PgDefaultAclRecord
     */
    public PgDefaultAclRecord(Long oid, Long defaclrole, Long defaclnamespace, String defaclobjtype, String[] defaclacl) {
        super(PgDefaultAcl.PG_DEFAULT_ACL);

        set(0, oid);
        set(1, defaclrole);
        set(2, defaclnamespace);
        set(3, defaclobjtype);
        set(4, defaclacl);
    }
}
