/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgEnum;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgEnumRecord extends TableRecordImpl<PgEnumRecord> implements Record4<Long, Long, Float, String> {

    private static final long serialVersionUID = 175269255;

    /**
     * Setter for <code>pg_catalog.pg_enum.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_enum.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_enum.enumtypid</code>.
     */
    public void setEnumtypid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_enum.enumtypid</code>.
     */
    public Long getEnumtypid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_enum.enumsortorder</code>.
     */
    public void setEnumsortorder(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_enum.enumsortorder</code>.
     */
    public Float getEnumsortorder() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_enum.enumlabel</code>.
     */
    public void setEnumlabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_enum.enumlabel</code>.
     */
    public String getEnumlabel() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Float, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Float, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgEnum.PG_ENUM.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgEnum.PG_ENUM.ENUMTYPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return PgEnum.PG_ENUM.ENUMSORTORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgEnum.PG_ENUM.ENUMLABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEnumtypid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getEnumsortorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEnumlabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgEnumRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgEnumRecord value2(Long value) {
        setEnumtypid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgEnumRecord value3(Float value) {
        setEnumsortorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgEnumRecord value4(String value) {
        setEnumlabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgEnumRecord values(Long value1, Long value2, Float value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgEnumRecord
     */
    public PgEnumRecord() {
        super(PgEnum.PG_ENUM);
    }

    /**
     * Create a detached, initialised PgEnumRecord
     */
    public PgEnumRecord(Long oid, Long enumtypid, Float enumsortorder, String enumlabel) {
        super(PgEnum.PG_ENUM);

        set(0, oid);
        set(1, enumtypid);
        set(2, enumsortorder);
        set(3, enumlabel);
    }
}
