/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgLargeobjectMetadata;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgLargeobjectMetadataRecord extends TableRecordImpl<PgLargeobjectMetadataRecord> implements Record3<Long, Long, String[]> {

    private static final long serialVersionUID = -891390242;

    /**
     * Setter for <code>pg_catalog.pg_largeobject_metadata.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_largeobject_metadata.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_largeobject_metadata.lomowner</code>.
     */
    public void setLomowner(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_largeobject_metadata.lomowner</code>.
     */
    public Long getLomowner() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_largeobject_metadata.lomacl</code>.
     */
    public void setLomacl(String[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_largeobject_metadata.lomacl</code>.
     */
    public String[] getLomacl() {
        return (String[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, String[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA.LOMOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field3() {
        return PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA.LOMACL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getLomowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value3() {
        return getLomacl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgLargeobjectMetadataRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgLargeobjectMetadataRecord value2(Long value) {
        setLomowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgLargeobjectMetadataRecord value3(String[] value) {
        setLomacl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgLargeobjectMetadataRecord values(Long value1, Long value2, String[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgLargeobjectMetadataRecord
     */
    public PgLargeobjectMetadataRecord() {
        super(PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA);
    }

    /**
     * Create a detached, initialised PgLargeobjectMetadataRecord
     */
    public PgLargeobjectMetadataRecord(Long oid, Long lomowner, String[] lomacl) {
        super(PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA);

        set(0, oid);
        set(1, lomowner);
        set(2, lomacl);
    }
}
