/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgPolicy;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPolicyRecord extends TableRecordImpl<PgPolicyRecord> implements Record8<Long, String, Long, String, Boolean, Long[], Object, Object> {

    private static final long serialVersionUID = -843039094;

    /**
     * Setter for <code>pg_catalog.pg_policy.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polname</code>.
     */
    public void setPolname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polname</code>.
     */
    public String getPolname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polrelid</code>.
     */
    public void setPolrelid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polrelid</code>.
     */
    public Long getPolrelid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polcmd</code>.
     */
    public void setPolcmd(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polcmd</code>.
     */
    public String getPolcmd() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polpermissive</code>.
     */
    public void setPolpermissive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polpermissive</code>.
     */
    public Boolean getPolpermissive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polroles</code>.
     */
    public void setPolroles(Long[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polroles</code>.
     */
    public Long[] getPolroles() {
        return (Long[]) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polqual</code>.
     */
    public void setPolqual(Object value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polqual</code>.
     */
    public Object getPolqual() {
        return (Object) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_policy.polwithcheck</code>.
     */
    public void setPolwithcheck(Object value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_policy.polwithcheck</code>.
     */
    public Object getPolwithcheck() {
        return (Object) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, Boolean, Long[], Object, Object> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, Boolean, Long[], Object, Object> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgPolicy.PG_POLICY.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgPolicy.PG_POLICY.POLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgPolicy.PG_POLICY.POLRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgPolicy.PG_POLICY.POLCMD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return PgPolicy.PG_POLICY.POLPERMISSIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field6() {
        return PgPolicy.PG_POLICY.POLROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return PgPolicy.PG_POLICY.POLQUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field8() {
        return PgPolicy.PG_POLICY.POLWITHCHECK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPolname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPolrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPolcmd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getPolpermissive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value6() {
        return getPolroles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return getPolqual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value8() {
        return getPolwithcheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value2(String value) {
        setPolname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value3(Long value) {
        setPolrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value4(String value) {
        setPolcmd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value5(Boolean value) {
        setPolpermissive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value6(Long[] value) {
        setPolroles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value7(Object value) {
        setPolqual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord value8(Object value) {
        setPolwithcheck(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPolicyRecord values(Long value1, String value2, Long value3, String value4, Boolean value5, Long[] value6, Object value7, Object value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPolicyRecord
     */
    public PgPolicyRecord() {
        super(PgPolicy.PG_POLICY);
    }

    /**
     * Create a detached, initialised PgPolicyRecord
     */
    public PgPolicyRecord(Long oid, String polname, Long polrelid, String polcmd, Boolean polpermissive, Long[] polroles, Object polqual, Object polwithcheck) {
        super(PgPolicy.PG_POLICY);

        set(0, oid);
        set(1, polname);
        set(2, polrelid);
        set(3, polcmd);
        set(4, polpermissive);
        set(5, polroles);
        set(6, polqual);
        set(7, polwithcheck);
    }
}
