/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgPublication;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublicationRecord extends TableRecordImpl<PgPublicationRecord> implements Record8<Long, String, Long, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 91566976;

    /**
     * Setter for <code>pg_catalog.pg_publication.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubname</code>.
     */
    public void setPubname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubname</code>.
     */
    public String getPubname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubowner</code>.
     */
    public void setPubowner(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubowner</code>.
     */
    public Long getPubowner() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.puballtables</code>.
     */
    public void setPuballtables(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.puballtables</code>.
     */
    public Boolean getPuballtables() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubinsert</code>.
     */
    public void setPubinsert(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubinsert</code>.
     */
    public Boolean getPubinsert() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubupdate</code>.
     */
    public void setPubupdate(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubupdate</code>.
     */
    public Boolean getPubupdate() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubdelete</code>.
     */
    public void setPubdelete(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubdelete</code>.
     */
    public Boolean getPubdelete() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication.pubtruncate</code>.
     */
    public void setPubtruncate(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication.pubtruncate</code>.
     */
    public Boolean getPubtruncate() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgPublication.PG_PUBLICATION.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgPublication.PG_PUBLICATION.PUBNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgPublication.PG_PUBLICATION.PUBOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return PgPublication.PG_PUBLICATION.PUBALLTABLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return PgPublication.PG_PUBLICATION.PUBINSERT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return PgPublication.PG_PUBLICATION.PUBUPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return PgPublication.PG_PUBLICATION.PUBDELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return PgPublication.PG_PUBLICATION.PUBTRUNCATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPubname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPubowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getPuballtables();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getPubinsert();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getPubupdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getPubdelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getPubtruncate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value2(String value) {
        setPubname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value3(Long value) {
        setPubowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value4(Boolean value) {
        setPuballtables(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value5(Boolean value) {
        setPubinsert(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value6(Boolean value) {
        setPubupdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value7(Boolean value) {
        setPubdelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord value8(Boolean value) {
        setPubtruncate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRecord values(Long value1, String value2, Long value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPublicationRecord
     */
    public PgPublicationRecord() {
        super(PgPublication.PG_PUBLICATION);
    }

    /**
     * Create a detached, initialised PgPublicationRecord
     */
    public PgPublicationRecord(Long oid, String pubname, Long pubowner, Boolean puballtables, Boolean pubinsert, Boolean pubupdate, Boolean pubdelete, Boolean pubtruncate) {
        super(PgPublication.PG_PUBLICATION);

        set(0, oid);
        set(1, pubname);
        set(2, pubowner);
        set(3, puballtables);
        set(4, pubinsert);
        set(5, pubupdate);
        set(6, pubdelete);
        set(7, pubtruncate);
    }
}
