/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgPublicationRel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublicationRelRecord extends TableRecordImpl<PgPublicationRelRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 489234914;

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.prpubid</code>.
     */
    public void setPrpubid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.prpubid</code>.
     */
    public Long getPrpubid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.prrelid</code>.
     */
    public void setPrrelid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.prrelid</code>.
     */
    public Long getPrrelid() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgPublicationRel.PG_PUBLICATION_REL.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRPUBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPrpubid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPrrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRelRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRelRecord value2(Long value) {
        setPrpubid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRelRecord value3(Long value) {
        setPrrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgPublicationRelRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPublicationRelRecord
     */
    public PgPublicationRelRecord() {
        super(PgPublicationRel.PG_PUBLICATION_REL);
    }

    /**
     * Create a detached, initialised PgPublicationRelRecord
     */
    public PgPublicationRelRecord(Long oid, Long prpubid, Long prrelid) {
        super(PgPublicationRel.PG_PUBLICATION_REL);

        set(0, oid);
        set(1, prpubid);
        set(2, prrelid);
    }
}
