/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgRewrite;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgRewriteRecord extends TableRecordImpl<PgRewriteRecord> implements Record8<Long, String, Long, String, String, Boolean, Object, Object> {

    private static final long serialVersionUID = 1985477138;

    /**
     * Setter for <code>pg_catalog.pg_rewrite.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.rulename</code>.
     */
    public void setRulename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.rulename</code>.
     */
    public String getRulename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.ev_class</code>.
     */
    public void setEvClass(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.ev_class</code>.
     */
    public Long getEvClass() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.ev_type</code>.
     */
    public void setEvType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.ev_type</code>.
     */
    public String getEvType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.ev_enabled</code>.
     */
    public void setEvEnabled(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.ev_enabled</code>.
     */
    public String getEvEnabled() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.is_instead</code>.
     */
    public void setIsInstead(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.is_instead</code>.
     */
    public Boolean getIsInstead() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.ev_qual</code>.
     */
    public void setEvQual(Object value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.ev_qual</code>.
     */
    public Object getEvQual() {
        return (Object) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_rewrite.ev_action</code>.
     */
    public void setEvAction(Object value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_rewrite.ev_action</code>.
     */
    public Object getEvAction() {
        return (Object) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, String, Boolean, Object, Object> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, String, Boolean, Object, Object> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgRewrite.PG_REWRITE.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgRewrite.PG_REWRITE.RULENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgRewrite.PG_REWRITE.EV_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgRewrite.PG_REWRITE.EV_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgRewrite.PG_REWRITE.EV_ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return PgRewrite.PG_REWRITE.IS_INSTEAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return PgRewrite.PG_REWRITE.EV_QUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field8() {
        return PgRewrite.PG_REWRITE.EV_ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRulename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getEvClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEvType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEvEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getIsInstead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return getEvQual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value8() {
        return getEvAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value2(String value) {
        setRulename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value3(Long value) {
        setEvClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value4(String value) {
        setEvType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value5(String value) {
        setEvEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value6(Boolean value) {
        setIsInstead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value7(Object value) {
        setEvQual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord value8(Object value) {
        setEvAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgRewriteRecord values(Long value1, String value2, Long value3, String value4, String value5, Boolean value6, Object value7, Object value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgRewriteRecord
     */
    public PgRewriteRecord() {
        super(PgRewrite.PG_REWRITE);
    }

    /**
     * Create a detached, initialised PgRewriteRecord
     */
    public PgRewriteRecord(Long oid, String rulename, Long evClass, String evType, String evEnabled, Boolean isInstead, Object evQual, Object evAction) {
        super(PgRewrite.PG_REWRITE);

        set(0, oid);
        set(1, rulename);
        set(2, evClass);
        set(3, evType);
        set(4, evEnabled);
        set(5, isInstead);
        set(6, evQual);
        set(7, evAction);
    }
}
