/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgStatGssapi;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatGssapiRecord extends TableRecordImpl<PgStatGssapiRecord> implements Record4<Integer, Boolean, String, Boolean> {

    private static final long serialVersionUID = -402890578;

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public void setGssAuthenticated(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public Boolean getGssAuthenticated() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public void setPrincipal(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public String getPrincipal() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public void setEncrypted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public Boolean getEncrypted() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Boolean, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Boolean, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PgStatGssapi.PG_STAT_GSSAPI.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return PgStatGssapi.PG_STAT_GSSAPI.GSS_AUTHENTICATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgStatGssapi.PG_STAT_GSSAPI.PRINCIPAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return PgStatGssapi.PG_STAT_GSSAPI.ENCRYPTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getGssAuthenticated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatGssapiRecord value1(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatGssapiRecord value2(Boolean value) {
        setGssAuthenticated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatGssapiRecord value3(String value) {
        setPrincipal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatGssapiRecord value4(Boolean value) {
        setEncrypted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatGssapiRecord values(Integer value1, Boolean value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatGssapiRecord
     */
    public PgStatGssapiRecord() {
        super(PgStatGssapi.PG_STAT_GSSAPI);
    }

    /**
     * Create a detached, initialised PgStatGssapiRecord
     */
    public PgStatGssapiRecord(Integer pid, Boolean gssAuthenticated, String principal, Boolean encrypted) {
        super(PgStatGssapi.PG_STAT_GSSAPI);

        set(0, pid);
        set(1, gssAuthenticated);
        set(2, principal);
        set(3, encrypted);
    }
}
