/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgStatProgressCluster;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatProgressClusterRecord extends TableRecordImpl<PgStatProgressClusterRecord> implements Record12<Integer, Long, String, Long, String, String, Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 51499218;

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.datid</code>.
     */
    public void setDatid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.datid</code>.
     */
    public Long getDatid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.datname</code>.
     */
    public void setDatname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.datname</code>.
     */
    public String getDatname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.relid</code>.
     */
    public void setRelid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.relid</code>.
     */
    public Long getRelid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.command</code>.
     */
    public void setCommand(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.command</code>.
     */
    public String getCommand() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.phase</code>.
     */
    public void setPhase(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.phase</code>.
     */
    public String getPhase() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.cluster_index_relid</code>.
     */
    public void setClusterIndexRelid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.cluster_index_relid</code>.
     */
    public Long getClusterIndexRelid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_scanned</code>.
     */
    public void setHeapTuplesScanned(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_scanned</code>.
     */
    public Long getHeapTuplesScanned() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_written</code>.
     */
    public void setHeapTuplesWritten(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_written</code>.
     */
    public Long getHeapTuplesWritten() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.heap_blks_total</code>.
     */
    public void setHeapBlksTotal(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.heap_blks_total</code>.
     */
    public Long getHeapBlksTotal() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.heap_blks_scanned</code>.
     */
    public void setHeapBlksScanned(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.heap_blks_scanned</code>.
     */
    public Long getHeapBlksScanned() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_cluster.index_rebuild_count</code>.
     */
    public void setIndexRebuildCount(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_cluster.index_rebuild_count</code>.
     */
    public Long getIndexRebuildCount() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Long, String, Long, String, String, Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Long, String, Long, String, String, Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.DATID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.DATNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.RELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.COMMAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.PHASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.CLUSTER_INDEX_RELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.HEAP_TUPLES_SCANNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.HEAP_TUPLES_WRITTEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.HEAP_BLKS_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.HEAP_BLKS_SCANNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER.INDEX_REBUILD_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDatid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDatname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getRelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCommand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getClusterIndexRelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getHeapTuplesScanned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getHeapTuplesWritten();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getHeapBlksTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getHeapBlksScanned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getIndexRebuildCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value1(Integer value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value2(Long value) {
        setDatid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value3(String value) {
        setDatname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value4(Long value) {
        setRelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value5(String value) {
        setCommand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value6(String value) {
        setPhase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value7(Long value) {
        setClusterIndexRelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value8(Long value) {
        setHeapTuplesScanned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value9(Long value) {
        setHeapTuplesWritten(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value10(Long value) {
        setHeapBlksTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value11(Long value) {
        setHeapBlksScanned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord value12(Long value) {
        setIndexRebuildCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressClusterRecord values(Integer value1, Long value2, String value3, Long value4, String value5, String value6, Long value7, Long value8, Long value9, Long value10, Long value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatProgressClusterRecord
     */
    public PgStatProgressClusterRecord() {
        super(PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER);
    }

    /**
     * Create a detached, initialised PgStatProgressClusterRecord
     */
    public PgStatProgressClusterRecord(Integer pid, Long datid, String datname, Long relid, String command, String phase, Long clusterIndexRelid, Long heapTuplesScanned, Long heapTuplesWritten, Long heapBlksTotal, Long heapBlksScanned, Long indexRebuildCount) {
        super(PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER);

        set(0, pid);
        set(1, datid);
        set(2, datname);
        set(3, relid);
        set(4, command);
        set(5, phase);
        set(6, clusterIndexRelid);
        set(7, heapTuplesScanned);
        set(8, heapTuplesWritten);
        set(9, heapBlksTotal);
        set(10, heapBlksScanned);
        set(11, indexRebuildCount);
    }
}
