/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgStatisticExt;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatisticExtRecord extends TableRecordImpl<PgStatisticExtRecord> implements Record7<Long, Long, String, Long, Long, Object[], String[]> {

    private static final long serialVersionUID = 1921764470;

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxrelid</code>.
     */
    public void setStxrelid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxrelid</code>.
     */
    public Long getStxrelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxname</code>.
     */
    public void setStxname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxname</code>.
     */
    public String getStxname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxnamespace</code>.
     */
    public void setStxnamespace(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxnamespace</code>.
     */
    public Long getStxnamespace() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxowner</code>.
     */
    public void setStxowner(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxowner</code>.
     */
    public Long getStxowner() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxkeys</code>.
     */
    public void setStxkeys(Object[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxkeys</code>.
     */
    public Object[] getStxkeys() {
        return (Object[]) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext.stxkind</code>.
     */
    public void setStxkind(String[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext.stxkind</code>.
     */
    public String[] getStxkind() {
        return (String[]) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, Long, Long, Object[], String[]> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, Long, Long, Object[], String[]> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgStatisticExt.PG_STATISTIC_EXT.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXNAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object[]> field6() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXKEYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field7() {
        return PgStatisticExt.PG_STATISTIC_EXT.STXKIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getStxrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStxname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getStxnamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getStxowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object[] value6() {
        return getStxkeys();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value7() {
        return getStxkind();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value2(Long value) {
        setStxrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value3(String value) {
        setStxname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value4(Long value) {
        setStxnamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value5(Long value) {
        setStxowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value6(Object[] value) {
        setStxkeys(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord value7(String[] value) {
        setStxkind(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtRecord values(Long value1, Long value2, String value3, Long value4, Long value5, Object[] value6, String[] value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatisticExtRecord
     */
    public PgStatisticExtRecord() {
        super(PgStatisticExt.PG_STATISTIC_EXT);
    }

    /**
     * Create a detached, initialised PgStatisticExtRecord
     */
    public PgStatisticExtRecord(Long oid, Long stxrelid, String stxname, Long stxnamespace, Long stxowner, Object[] stxkeys, String[] stxkind) {
        super(PgStatisticExt.PG_STATISTIC_EXT);

        set(0, oid);
        set(1, stxrelid);
        set(2, stxname);
        set(3, stxnamespace);
        set(4, stxowner);
        set(5, stxkeys);
        set(6, stxkind);
    }
}
