/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgSubscription;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgSubscriptionRecord extends TableRecordImpl<PgSubscriptionRecord> implements Record9<Long, Long, String, Long, Boolean, String, String, String, String[]> {

    private static final long serialVersionUID = -1528658709;

    /**
     * Setter for <code>pg_catalog.pg_subscription.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subdbid</code>.
     */
    public void setSubdbid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subdbid</code>.
     */
    public Long getSubdbid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subname</code>.
     */
    public void setSubname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subname</code>.
     */
    public String getSubname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subowner</code>.
     */
    public void setSubowner(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subowner</code>.
     */
    public Long getSubowner() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subenabled</code>.
     */
    public void setSubenabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subenabled</code>.
     */
    public Boolean getSubenabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subconninfo</code>.
     */
    public void setSubconninfo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subconninfo</code>.
     */
    public String getSubconninfo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subslotname</code>.
     */
    public void setSubslotname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subslotname</code>.
     */
    public String getSubslotname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subsynccommit</code>.
     */
    public void setSubsynccommit(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subsynccommit</code>.
     */
    public String getSubsynccommit() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_subscription.subpublications</code>.
     */
    public void setSubpublications(String[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_subscription.subpublications</code>.
     */
    public String[] getSubpublications() {
        return (String[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, Long, Boolean, String, String, String, String[]> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, Long, Boolean, String, String, String, String[]> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgSubscription.PG_SUBSCRIPTION.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgSubscription.PG_SUBSCRIPTION.SUBDBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgSubscription.PG_SUBSCRIPTION.SUBNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgSubscription.PG_SUBSCRIPTION.SUBOWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return PgSubscription.PG_SUBSCRIPTION.SUBENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgSubscription.PG_SUBSCRIPTION.SUBCONNINFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PgSubscription.PG_SUBSCRIPTION.SUBSLOTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PgSubscription.PG_SUBSCRIPTION.SUBSYNCCOMMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field9() {
        return PgSubscription.PG_SUBSCRIPTION.SUBPUBLICATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSubdbid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSubname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSubowner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getSubenabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSubconninfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSubslotname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSubsynccommit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value9() {
        return getSubpublications();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value2(Long value) {
        setSubdbid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value3(String value) {
        setSubname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value4(Long value) {
        setSubowner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value5(Boolean value) {
        setSubenabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value6(String value) {
        setSubconninfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value7(String value) {
        setSubslotname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value8(String value) {
        setSubsynccommit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord value9(String[] value) {
        setSubpublications(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgSubscriptionRecord values(Long value1, Long value2, String value3, Long value4, Boolean value5, String value6, String value7, String value8, String[] value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgSubscriptionRecord
     */
    public PgSubscriptionRecord() {
        super(PgSubscription.PG_SUBSCRIPTION);
    }

    /**
     * Create a detached, initialised PgSubscriptionRecord
     */
    public PgSubscriptionRecord(Long oid, Long subdbid, String subname, Long subowner, Boolean subenabled, String subconninfo, String subslotname, String subsynccommit, String[] subpublications) {
        super(PgSubscription.PG_SUBSCRIPTION);

        set(0, oid);
        set(1, subdbid);
        set(2, subname);
        set(3, subowner);
        set(4, subenabled);
        set(5, subconninfo);
        set(6, subslotname);
        set(7, subsynccommit);
        set(8, subpublications);
    }
}
