/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgTrigger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTriggerRecord extends TableRecordImpl<PgTriggerRecord> implements Record18<Long, Long, String, Long, Short, String, Boolean, Long, Long, Long, Boolean, Boolean, Short, Object[], byte[], Object, String, String> {

    private static final long serialVersionUID = -307159655;

    /**
     * Setter for <code>pg_catalog.pg_trigger.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgrelid</code>.
     */
    public void setTgrelid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgrelid</code>.
     */
    public Long getTgrelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgname</code>.
     */
    public void setTgname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgname</code>.
     */
    public String getTgname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgfoid</code>.
     */
    public void setTgfoid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgfoid</code>.
     */
    public Long getTgfoid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgtype</code>.
     */
    public void setTgtype(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgtype</code>.
     */
    public Short getTgtype() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgenabled</code>.
     */
    public void setTgenabled(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgenabled</code>.
     */
    public String getTgenabled() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgisinternal</code>.
     */
    public void setTgisinternal(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgisinternal</code>.
     */
    public Boolean getTgisinternal() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgconstrrelid</code>.
     */
    public void setTgconstrrelid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgconstrrelid</code>.
     */
    public Long getTgconstrrelid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgconstrindid</code>.
     */
    public void setTgconstrindid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgconstrindid</code>.
     */
    public Long getTgconstrindid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgconstraint</code>.
     */
    public void setTgconstraint(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgconstraint</code>.
     */
    public Long getTgconstraint() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgdeferrable</code>.
     */
    public void setTgdeferrable(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgdeferrable</code>.
     */
    public Boolean getTgdeferrable() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tginitdeferred</code>.
     */
    public void setTginitdeferred(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tginitdeferred</code>.
     */
    public Boolean getTginitdeferred() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgnargs</code>.
     */
    public void setTgnargs(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgnargs</code>.
     */
    public Short getTgnargs() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgattr</code>.
     */
    public void setTgattr(Object[] value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgattr</code>.
     */
    public Object[] getTgattr() {
        return (Object[]) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgargs</code>.
     */
    public void setTgargs(byte[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgargs</code>.
     */
    public byte[] getTgargs() {
        return (byte[]) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgqual</code>.
     */
    public void setTgqual(Object value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgqual</code>.
     */
    public Object getTgqual() {
        return (Object) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgoldtable</code>.
     */
    public void setTgoldtable(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgoldtable</code>.
     */
    public String getTgoldtable() {
        return (String) get(16);
    }

    /**
     * Setter for <code>pg_catalog.pg_trigger.tgnewtable</code>.
     */
    public void setTgnewtable(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_trigger.tgnewtable</code>.
     */
    public String getTgnewtable() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, Long, Short, String, Boolean, Long, Long, Long, Boolean, Boolean, Short, Object[], byte[], Object, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, Long, Short, String, Boolean, Long, Long, Long, Boolean, Boolean, Short, Object[], byte[], Object, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgTrigger.PG_TRIGGER.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PgTrigger.PG_TRIGGER.TGRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PgTrigger.PG_TRIGGER.TGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PgTrigger.PG_TRIGGER.TGFOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return PgTrigger.PG_TRIGGER.TGTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgTrigger.PG_TRIGGER.TGENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return PgTrigger.PG_TRIGGER.TGISINTERNAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return PgTrigger.PG_TRIGGER.TGCONSTRRELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PgTrigger.PG_TRIGGER.TGCONSTRINDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return PgTrigger.PG_TRIGGER.TGCONSTRAINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return PgTrigger.PG_TRIGGER.TGDEFERRABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return PgTrigger.PG_TRIGGER.TGINITDEFERRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field13() {
        return PgTrigger.PG_TRIGGER.TGNARGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object[]> field14() {
        return PgTrigger.PG_TRIGGER.TGATTR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field15() {
        return PgTrigger.PG_TRIGGER.TGARGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field16() {
        return PgTrigger.PG_TRIGGER.TGQUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return PgTrigger.PG_TRIGGER.TGOLDTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return PgTrigger.PG_TRIGGER.TGNEWTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTgrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTgname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getTgfoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getTgtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTgenabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getTgisinternal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getTgconstrrelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getTgconstrindid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getTgconstraint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getTgdeferrable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getTginitdeferred();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value13() {
        return getTgnargs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object[] value14() {
        return getTgattr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value15() {
        return getTgargs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value16() {
        return getTgqual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getTgoldtable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getTgnewtable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value2(Long value) {
        setTgrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value3(String value) {
        setTgname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value4(Long value) {
        setTgfoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value5(Short value) {
        setTgtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value6(String value) {
        setTgenabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value7(Boolean value) {
        setTgisinternal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value8(Long value) {
        setTgconstrrelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value9(Long value) {
        setTgconstrindid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value10(Long value) {
        setTgconstraint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value11(Boolean value) {
        setTgdeferrable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value12(Boolean value) {
        setTginitdeferred(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value13(Short value) {
        setTgnargs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value14(Object[] value) {
        setTgattr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value15(byte[] value) {
        setTgargs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value16(Object value) {
        setTgqual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value17(String value) {
        setTgoldtable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord value18(String value) {
        setTgnewtable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTriggerRecord values(Long value1, Long value2, String value3, Long value4, Short value5, String value6, Boolean value7, Long value8, Long value9, Long value10, Boolean value11, Boolean value12, Short value13, Object[] value14, byte[] value15, Object value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgTriggerRecord
     */
    public PgTriggerRecord() {
        super(PgTrigger.PG_TRIGGER);
    }

    /**
     * Create a detached, initialised PgTriggerRecord
     */
    public PgTriggerRecord(Long oid, Long tgrelid, String tgname, Long tgfoid, Short tgtype, String tgenabled, Boolean tgisinternal, Long tgconstrrelid, Long tgconstrindid, Long tgconstraint, Boolean tgdeferrable, Boolean tginitdeferred, Short tgnargs, Object[] tgattr, byte[] tgargs, Object tgqual, String tgoldtable, String tgnewtable) {
        super(PgTrigger.PG_TRIGGER);

        set(0, oid);
        set(1, tgrelid);
        set(2, tgname);
        set(3, tgfoid);
        set(4, tgtype);
        set(5, tgenabled);
        set(6, tgisinternal);
        set(7, tgconstrrelid);
        set(8, tgconstrindid);
        set(9, tgconstraint);
        set(10, tgdeferrable);
        set(11, tginitdeferred);
        set(12, tgnargs);
        set(13, tgattr);
        set(14, tgargs);
        set(15, tgqual);
        set(16, tgoldtable);
        set(17, tgnewtable);
    }
}
