/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables.records;


import Jooq.pg_catalog.tables.PgTsParser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTsParserRecord extends TableRecordImpl<PgTsParserRecord> implements Record8<Long, String, Long, String, String, String, String, String> {

    private static final long serialVersionUID = -1490827127;

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prsname</code>.
     */
    public void setPrsname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prsname</code>.
     */
    public String getPrsname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prsnamespace</code>.
     */
    public void setPrsnamespace(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prsnamespace</code>.
     */
    public Long getPrsnamespace() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prsstart</code>.
     */
    public void setPrsstart(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prsstart</code>.
     */
    public String getPrsstart() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prstoken</code>.
     */
    public void setPrstoken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prstoken</code>.
     */
    public String getPrstoken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prsend</code>.
     */
    public void setPrsend(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prsend</code>.
     */
    public String getPrsend() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prsheadline</code>.
     */
    public void setPrsheadline(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prsheadline</code>.
     */
    public String getPrsheadline() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_ts_parser.prslextype</code>.
     */
    public void setPrslextype(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ts_parser.prslextype</code>.
     */
    public String getPrslextype() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PgTsParser.PG_TS_PARSER.OID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PgTsParser.PG_TS_PARSER.PRSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PgTsParser.PG_TS_PARSER.PRSNAMESPACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PgTsParser.PG_TS_PARSER.PRSSTART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PgTsParser.PG_TS_PARSER.PRSTOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PgTsParser.PG_TS_PARSER.PRSEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return PgTsParser.PG_TS_PARSER.PRSHEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PgTsParser.PG_TS_PARSER.PRSLEXTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getOid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPrsnamespace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPrsstart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPrstoken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPrsend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPrsheadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPrslextype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value1(Long value) {
        setOid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value2(String value) {
        setPrsname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value3(Long value) {
        setPrsnamespace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value4(String value) {
        setPrsstart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value5(String value) {
        setPrstoken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value6(String value) {
        setPrsend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value7(String value) {
        setPrsheadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord value8(String value) {
        setPrslextype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgTsParserRecord values(Long value1, String value2, Long value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgTsParserRecord
     */
    public PgTsParserRecord() {
        super(PgTsParser.PG_TS_PARSER);
    }

    /**
     * Create a detached, initialised PgTsParserRecord
     */
    public PgTsParserRecord(Long oid, String prsname, Long prsnamespace, String prsstart, String prstoken, String prsend, String prsheadline, String prslextype) {
        super(PgTsParser.PG_TS_PARSER);

        set(0, oid);
        set(1, prsname);
        set(2, prsnamespace);
        set(3, prsstart);
        set(4, prstoken);
        set(5, prsend);
        set(6, prsheadline);
        set(7, prslextype);
    }
}
