/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog;


import Jooq.pg_catalog.tables.PgAggregate;
import Jooq.pg_catalog.tables.PgAm;
import Jooq.pg_catalog.tables.PgAmop;
import Jooq.pg_catalog.tables.PgAmproc;
import Jooq.pg_catalog.tables.PgAttrdef;
import Jooq.pg_catalog.tables.PgAttribute;
import Jooq.pg_catalog.tables.PgAuthMembers;
import Jooq.pg_catalog.tables.PgAuthid;
import Jooq.pg_catalog.tables.PgAvailableExtensionVersions;
import Jooq.pg_catalog.tables.PgAvailableExtensions;
import Jooq.pg_catalog.tables.PgCast;
import Jooq.pg_catalog.tables.PgClass;
import Jooq.pg_catalog.tables.PgCollation;
import Jooq.pg_catalog.tables.PgConfig;
import Jooq.pg_catalog.tables.PgConstraint;
import Jooq.pg_catalog.tables.PgConversion;
import Jooq.pg_catalog.tables.PgCursors;
import Jooq.pg_catalog.tables.PgDatabase;
import Jooq.pg_catalog.tables.PgDbRoleSetting;
import Jooq.pg_catalog.tables.PgDefaultAcl;
import Jooq.pg_catalog.tables.PgDepend;
import Jooq.pg_catalog.tables.PgDescription;
import Jooq.pg_catalog.tables.PgEnum;
import Jooq.pg_catalog.tables.PgEventTrigger;
import Jooq.pg_catalog.tables.PgExtension;
import Jooq.pg_catalog.tables.PgFileSettings;
import Jooq.pg_catalog.tables.PgForeignDataWrapper;
import Jooq.pg_catalog.tables.PgForeignServer;
import Jooq.pg_catalog.tables.PgForeignTable;
import Jooq.pg_catalog.tables.PgGroup;
import Jooq.pg_catalog.tables.PgHbaFileRules;
import Jooq.pg_catalog.tables.PgIndex;
import Jooq.pg_catalog.tables.PgIndexes;
import Jooq.pg_catalog.tables.PgInherits;
import Jooq.pg_catalog.tables.PgInitPrivs;
import Jooq.pg_catalog.tables.PgLanguage;
import Jooq.pg_catalog.tables.PgLargeobject;
import Jooq.pg_catalog.tables.PgLargeobjectMetadata;
import Jooq.pg_catalog.tables.PgLocks;
import Jooq.pg_catalog.tables.PgMatviews;
import Jooq.pg_catalog.tables.PgNamespace;
import Jooq.pg_catalog.tables.PgOpclass;
import Jooq.pg_catalog.tables.PgOperator;
import Jooq.pg_catalog.tables.PgOpfamily;
import Jooq.pg_catalog.tables.PgPartitionedTable;
import Jooq.pg_catalog.tables.PgPltemplate;
import Jooq.pg_catalog.tables.PgPolicies;
import Jooq.pg_catalog.tables.PgPolicy;
import Jooq.pg_catalog.tables.PgPreparedStatements;
import Jooq.pg_catalog.tables.PgPreparedXacts;
import Jooq.pg_catalog.tables.PgProc;
import Jooq.pg_catalog.tables.PgPublication;
import Jooq.pg_catalog.tables.PgPublicationRel;
import Jooq.pg_catalog.tables.PgPublicationTables;
import Jooq.pg_catalog.tables.PgRange;
import Jooq.pg_catalog.tables.PgReplicationOrigin;
import Jooq.pg_catalog.tables.PgReplicationOriginStatus;
import Jooq.pg_catalog.tables.PgReplicationSlots;
import Jooq.pg_catalog.tables.PgRewrite;
import Jooq.pg_catalog.tables.PgRoles;
import Jooq.pg_catalog.tables.PgRules;
import Jooq.pg_catalog.tables.PgSeclabel;
import Jooq.pg_catalog.tables.PgSeclabels;
import Jooq.pg_catalog.tables.PgSequence;
import Jooq.pg_catalog.tables.PgSequences;
import Jooq.pg_catalog.tables.PgSettings;
import Jooq.pg_catalog.tables.PgShadow;
import Jooq.pg_catalog.tables.PgShdepend;
import Jooq.pg_catalog.tables.PgShdescription;
import Jooq.pg_catalog.tables.PgShseclabel;
import Jooq.pg_catalog.tables.PgStatActivity;
import Jooq.pg_catalog.tables.PgStatAllIndexes;
import Jooq.pg_catalog.tables.PgStatAllTables;
import Jooq.pg_catalog.tables.PgStatArchiver;
import Jooq.pg_catalog.tables.PgStatBgwriter;
import Jooq.pg_catalog.tables.PgStatDatabase;
import Jooq.pg_catalog.tables.PgStatDatabaseConflicts;
import Jooq.pg_catalog.tables.PgStatGssapi;
import Jooq.pg_catalog.tables.PgStatProgressCluster;
import Jooq.pg_catalog.tables.PgStatProgressCreateIndex;
import Jooq.pg_catalog.tables.PgStatProgressVacuum;
import Jooq.pg_catalog.tables.PgStatReplication;
import Jooq.pg_catalog.tables.PgStatSsl;
import Jooq.pg_catalog.tables.PgStatSubscription;
import Jooq.pg_catalog.tables.PgStatSysIndexes;
import Jooq.pg_catalog.tables.PgStatSysTables;
import Jooq.pg_catalog.tables.PgStatUserFunctions;
import Jooq.pg_catalog.tables.PgStatUserIndexes;
import Jooq.pg_catalog.tables.PgStatUserTables;
import Jooq.pg_catalog.tables.PgStatWalReceiver;
import Jooq.pg_catalog.tables.PgStatXactAllTables;
import Jooq.pg_catalog.tables.PgStatXactSysTables;
import Jooq.pg_catalog.tables.PgStatXactUserFunctions;
import Jooq.pg_catalog.tables.PgStatXactUserTables;
import Jooq.pg_catalog.tables.PgStatioAllIndexes;
import Jooq.pg_catalog.tables.PgStatioAllSequences;
import Jooq.pg_catalog.tables.PgStatioAllTables;
import Jooq.pg_catalog.tables.PgStatioSysIndexes;
import Jooq.pg_catalog.tables.PgStatioSysSequences;
import Jooq.pg_catalog.tables.PgStatioSysTables;
import Jooq.pg_catalog.tables.PgStatioUserIndexes;
import Jooq.pg_catalog.tables.PgStatioUserSequences;
import Jooq.pg_catalog.tables.PgStatioUserTables;
import Jooq.pg_catalog.tables.PgStatistic;
import Jooq.pg_catalog.tables.PgStatisticExt;
import Jooq.pg_catalog.tables.PgStatisticExtData;
import Jooq.pg_catalog.tables.PgStats;
import Jooq.pg_catalog.tables.PgStatsExt;
import Jooq.pg_catalog.tables.PgSubscription;
import Jooq.pg_catalog.tables.PgSubscriptionRel;
import Jooq.pg_catalog.tables.PgTables;
import Jooq.pg_catalog.tables.PgTablespace;
import Jooq.pg_catalog.tables.PgTimezoneAbbrevs;
import Jooq.pg_catalog.tables.PgTimezoneNames;
import Jooq.pg_catalog.tables.PgTransform;
import Jooq.pg_catalog.tables.PgTrigger;
import Jooq.pg_catalog.tables.PgTsConfig;
import Jooq.pg_catalog.tables.PgTsConfigMap;
import Jooq.pg_catalog.tables.PgTsDict;
import Jooq.pg_catalog.tables.PgTsParser;
import Jooq.pg_catalog.tables.PgTsTemplate;
import Jooq.pg_catalog.tables.PgType;
import Jooq.pg_catalog.tables.PgUser;
import Jooq.pg_catalog.tables.PgUserMapping;
import Jooq.pg_catalog.tables.PgUserMappings;
import Jooq.pg_catalog.tables.PgViews;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pg_catalog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pg_catalog.pg_aggregate</code>.
     */
    public static final PgAggregate PG_AGGREGATE = Jooq.pg_catalog.tables.PgAggregate.PG_AGGREGATE;

    /**
     * The table <code>pg_catalog.pg_am</code>.
     */
    public static final PgAm PG_AM = Jooq.pg_catalog.tables.PgAm.PG_AM;

    /**
     * The table <code>pg_catalog.pg_amop</code>.
     */
    public static final PgAmop PG_AMOP = Jooq.pg_catalog.tables.PgAmop.PG_AMOP;

    /**
     * The table <code>pg_catalog.pg_amproc</code>.
     */
    public static final PgAmproc PG_AMPROC = Jooq.pg_catalog.tables.PgAmproc.PG_AMPROC;

    /**
     * The table <code>pg_catalog.pg_attrdef</code>.
     */
    public static final PgAttrdef PG_ATTRDEF = Jooq.pg_catalog.tables.PgAttrdef.PG_ATTRDEF;

    /**
     * The table <code>pg_catalog.pg_attribute</code>.
     */
    public static final PgAttribute PG_ATTRIBUTE = Jooq.pg_catalog.tables.PgAttribute.PG_ATTRIBUTE;

    /**
     * The table <code>pg_catalog.pg_auth_members</code>.
     */
    public static final PgAuthMembers PG_AUTH_MEMBERS = Jooq.pg_catalog.tables.PgAuthMembers.PG_AUTH_MEMBERS;

    /**
     * The table <code>pg_catalog.pg_authid</code>.
     */
    public static final PgAuthid PG_AUTHID = Jooq.pg_catalog.tables.PgAuthid.PG_AUTHID;

    /**
     * The table <code>pg_catalog.pg_available_extension_versions</code>.
     */
    public static final PgAvailableExtensionVersions PG_AVAILABLE_EXTENSION_VERSIONS = Jooq.pg_catalog.tables.PgAvailableExtensionVersions.PG_AVAILABLE_EXTENSION_VERSIONS;

    /**
     * The table <code>pg_catalog.pg_available_extensions</code>.
     */
    public static final PgAvailableExtensions PG_AVAILABLE_EXTENSIONS = Jooq.pg_catalog.tables.PgAvailableExtensions.PG_AVAILABLE_EXTENSIONS;

    /**
     * The table <code>pg_catalog.pg_cast</code>.
     */
    public static final PgCast PG_CAST = Jooq.pg_catalog.tables.PgCast.PG_CAST;

    /**
     * The table <code>pg_catalog.pg_class</code>.
     */
    public static final PgClass PG_CLASS = Jooq.pg_catalog.tables.PgClass.PG_CLASS;

    /**
     * The table <code>pg_catalog.pg_collation</code>.
     */
    public static final PgCollation PG_COLLATION = Jooq.pg_catalog.tables.PgCollation.PG_COLLATION;

    /**
     * The table <code>pg_catalog.pg_config</code>.
     */
    public static final PgConfig PG_CONFIG = Jooq.pg_catalog.tables.PgConfig.PG_CONFIG;

    /**
     * The table <code>pg_catalog.pg_constraint</code>.
     */
    public static final PgConstraint PG_CONSTRAINT = Jooq.pg_catalog.tables.PgConstraint.PG_CONSTRAINT;

    /**
     * The table <code>pg_catalog.pg_conversion</code>.
     */
    public static final PgConversion PG_CONVERSION = Jooq.pg_catalog.tables.PgConversion.PG_CONVERSION;

    /**
     * The table <code>pg_catalog.pg_cursors</code>.
     */
    public static final PgCursors PG_CURSORS = Jooq.pg_catalog.tables.PgCursors.PG_CURSORS;

    /**
     * The table <code>pg_catalog.pg_database</code>.
     */
    public static final PgDatabase PG_DATABASE = Jooq.pg_catalog.tables.PgDatabase.PG_DATABASE;

    /**
     * The table <code>pg_catalog.pg_db_role_setting</code>.
     */
    public static final PgDbRoleSetting PG_DB_ROLE_SETTING = Jooq.pg_catalog.tables.PgDbRoleSetting.PG_DB_ROLE_SETTING;

    /**
     * The table <code>pg_catalog.pg_default_acl</code>.
     */
    public static final PgDefaultAcl PG_DEFAULT_ACL = Jooq.pg_catalog.tables.PgDefaultAcl.PG_DEFAULT_ACL;

    /**
     * The table <code>pg_catalog.pg_depend</code>.
     */
    public static final PgDepend PG_DEPEND = Jooq.pg_catalog.tables.PgDepend.PG_DEPEND;

    /**
     * The table <code>pg_catalog.pg_description</code>.
     */
    public static final PgDescription PG_DESCRIPTION = Jooq.pg_catalog.tables.PgDescription.PG_DESCRIPTION;

    /**
     * The table <code>pg_catalog.pg_enum</code>.
     */
    public static final PgEnum PG_ENUM = Jooq.pg_catalog.tables.PgEnum.PG_ENUM;

    /**
     * The table <code>pg_catalog.pg_event_trigger</code>.
     */
    public static final PgEventTrigger PG_EVENT_TRIGGER = Jooq.pg_catalog.tables.PgEventTrigger.PG_EVENT_TRIGGER;

    /**
     * The table <code>pg_catalog.pg_extension</code>.
     */
    public static final PgExtension PG_EXTENSION = Jooq.pg_catalog.tables.PgExtension.PG_EXTENSION;

    /**
     * The table <code>pg_catalog.pg_file_settings</code>.
     */
    public static final PgFileSettings PG_FILE_SETTINGS = Jooq.pg_catalog.tables.PgFileSettings.PG_FILE_SETTINGS;

    /**
     * The table <code>pg_catalog.pg_foreign_data_wrapper</code>.
     */
    public static final PgForeignDataWrapper PG_FOREIGN_DATA_WRAPPER = Jooq.pg_catalog.tables.PgForeignDataWrapper.PG_FOREIGN_DATA_WRAPPER;

    /**
     * The table <code>pg_catalog.pg_foreign_server</code>.
     */
    public static final PgForeignServer PG_FOREIGN_SERVER = Jooq.pg_catalog.tables.PgForeignServer.PG_FOREIGN_SERVER;

    /**
     * The table <code>pg_catalog.pg_foreign_table</code>.
     */
    public static final PgForeignTable PG_FOREIGN_TABLE = Jooq.pg_catalog.tables.PgForeignTable.PG_FOREIGN_TABLE;

    /**
     * The table <code>pg_catalog.pg_group</code>.
     */
    public static final PgGroup PG_GROUP = Jooq.pg_catalog.tables.PgGroup.PG_GROUP;

    /**
     * The table <code>pg_catalog.pg_hba_file_rules</code>.
     */
    public static final PgHbaFileRules PG_HBA_FILE_RULES = Jooq.pg_catalog.tables.PgHbaFileRules.PG_HBA_FILE_RULES;

    /**
     * The table <code>pg_catalog.pg_index</code>.
     */
    public static final PgIndex PG_INDEX = Jooq.pg_catalog.tables.PgIndex.PG_INDEX;

    /**
     * The table <code>pg_catalog.pg_indexes</code>.
     */
    public static final PgIndexes PG_INDEXES = Jooq.pg_catalog.tables.PgIndexes.PG_INDEXES;

    /**
     * The table <code>pg_catalog.pg_inherits</code>.
     */
    public static final PgInherits PG_INHERITS = Jooq.pg_catalog.tables.PgInherits.PG_INHERITS;

    /**
     * The table <code>pg_catalog.pg_init_privs</code>.
     */
    public static final PgInitPrivs PG_INIT_PRIVS = Jooq.pg_catalog.tables.PgInitPrivs.PG_INIT_PRIVS;

    /**
     * The table <code>pg_catalog.pg_language</code>.
     */
    public static final PgLanguage PG_LANGUAGE = Jooq.pg_catalog.tables.PgLanguage.PG_LANGUAGE;

    /**
     * The table <code>pg_catalog.pg_largeobject</code>.
     */
    public static final PgLargeobject PG_LARGEOBJECT = Jooq.pg_catalog.tables.PgLargeobject.PG_LARGEOBJECT;

    /**
     * The table <code>pg_catalog.pg_largeobject_metadata</code>.
     */
    public static final PgLargeobjectMetadata PG_LARGEOBJECT_METADATA = Jooq.pg_catalog.tables.PgLargeobjectMetadata.PG_LARGEOBJECT_METADATA;

    /**
     * The table <code>pg_catalog.pg_locks</code>.
     */
    public static final PgLocks PG_LOCKS = Jooq.pg_catalog.tables.PgLocks.PG_LOCKS;

    /**
     * The table <code>pg_catalog.pg_matviews</code>.
     */
    public static final PgMatviews PG_MATVIEWS = Jooq.pg_catalog.tables.PgMatviews.PG_MATVIEWS;

    /**
     * The table <code>pg_catalog.pg_namespace</code>.
     */
    public static final PgNamespace PG_NAMESPACE = Jooq.pg_catalog.tables.PgNamespace.PG_NAMESPACE;

    /**
     * The table <code>pg_catalog.pg_opclass</code>.
     */
    public static final PgOpclass PG_OPCLASS = Jooq.pg_catalog.tables.PgOpclass.PG_OPCLASS;

    /**
     * The table <code>pg_catalog.pg_operator</code>.
     */
    public static final PgOperator PG_OPERATOR = Jooq.pg_catalog.tables.PgOperator.PG_OPERATOR;

    /**
     * The table <code>pg_catalog.pg_opfamily</code>.
     */
    public static final PgOpfamily PG_OPFAMILY = Jooq.pg_catalog.tables.PgOpfamily.PG_OPFAMILY;

    /**
     * The table <code>pg_catalog.pg_partitioned_table</code>.
     */
    public static final PgPartitionedTable PG_PARTITIONED_TABLE = Jooq.pg_catalog.tables.PgPartitionedTable.PG_PARTITIONED_TABLE;

    /**
     * The table <code>pg_catalog.pg_pltemplate</code>.
     */
    public static final PgPltemplate PG_PLTEMPLATE = Jooq.pg_catalog.tables.PgPltemplate.PG_PLTEMPLATE;

    /**
     * The table <code>pg_catalog.pg_policies</code>.
     */
    public static final PgPolicies PG_POLICIES = Jooq.pg_catalog.tables.PgPolicies.PG_POLICIES;

    /**
     * The table <code>pg_catalog.pg_policy</code>.
     */
    public static final PgPolicy PG_POLICY = Jooq.pg_catalog.tables.PgPolicy.PG_POLICY;

    /**
     * The table <code>pg_catalog.pg_prepared_statements</code>.
     */
    public static final PgPreparedStatements PG_PREPARED_STATEMENTS = Jooq.pg_catalog.tables.PgPreparedStatements.PG_PREPARED_STATEMENTS;

    /**
     * The table <code>pg_catalog.pg_prepared_xacts</code>.
     */
    public static final PgPreparedXacts PG_PREPARED_XACTS = Jooq.pg_catalog.tables.PgPreparedXacts.PG_PREPARED_XACTS;

    /**
     * The table <code>pg_catalog.pg_proc</code>.
     */
    public static final PgProc PG_PROC = Jooq.pg_catalog.tables.PgProc.PG_PROC;

    /**
     * The table <code>pg_catalog.pg_publication</code>.
     */
    public static final PgPublication PG_PUBLICATION = Jooq.pg_catalog.tables.PgPublication.PG_PUBLICATION;

    /**
     * The table <code>pg_catalog.pg_publication_rel</code>.
     */
    public static final PgPublicationRel PG_PUBLICATION_REL = Jooq.pg_catalog.tables.PgPublicationRel.PG_PUBLICATION_REL;

    /**
     * The table <code>pg_catalog.pg_publication_tables</code>.
     */
    public static final PgPublicationTables PG_PUBLICATION_TABLES = Jooq.pg_catalog.tables.PgPublicationTables.PG_PUBLICATION_TABLES;

    /**
     * The table <code>pg_catalog.pg_range</code>.
     */
    public static final PgRange PG_RANGE = Jooq.pg_catalog.tables.PgRange.PG_RANGE;

    /**
     * The table <code>pg_catalog.pg_replication_origin</code>.
     */
    public static final PgReplicationOrigin PG_REPLICATION_ORIGIN = Jooq.pg_catalog.tables.PgReplicationOrigin.PG_REPLICATION_ORIGIN;

    /**
     * The table <code>pg_catalog.pg_replication_origin_status</code>.
     */
    public static final PgReplicationOriginStatus PG_REPLICATION_ORIGIN_STATUS = Jooq.pg_catalog.tables.PgReplicationOriginStatus.PG_REPLICATION_ORIGIN_STATUS;

    /**
     * The table <code>pg_catalog.pg_replication_slots</code>.
     */
    public static final PgReplicationSlots PG_REPLICATION_SLOTS = Jooq.pg_catalog.tables.PgReplicationSlots.PG_REPLICATION_SLOTS;

    /**
     * The table <code>pg_catalog.pg_rewrite</code>.
     */
    public static final PgRewrite PG_REWRITE = Jooq.pg_catalog.tables.PgRewrite.PG_REWRITE;

    /**
     * The table <code>pg_catalog.pg_roles</code>.
     */
    public static final PgRoles PG_ROLES = Jooq.pg_catalog.tables.PgRoles.PG_ROLES;

    /**
     * The table <code>pg_catalog.pg_rules</code>.
     */
    public static final PgRules PG_RULES = Jooq.pg_catalog.tables.PgRules.PG_RULES;

    /**
     * The table <code>pg_catalog.pg_seclabel</code>.
     */
    public static final PgSeclabel PG_SECLABEL = Jooq.pg_catalog.tables.PgSeclabel.PG_SECLABEL;

    /**
     * The table <code>pg_catalog.pg_seclabels</code>.
     */
    public static final PgSeclabels PG_SECLABELS = Jooq.pg_catalog.tables.PgSeclabels.PG_SECLABELS;

    /**
     * The table <code>pg_catalog.pg_sequence</code>.
     */
    public static final PgSequence PG_SEQUENCE = Jooq.pg_catalog.tables.PgSequence.PG_SEQUENCE;

    /**
     * The table <code>pg_catalog.pg_sequences</code>.
     */
    public static final PgSequences PG_SEQUENCES = Jooq.pg_catalog.tables.PgSequences.PG_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_settings</code>.
     */
    public static final PgSettings PG_SETTINGS = Jooq.pg_catalog.tables.PgSettings.PG_SETTINGS;

    /**
     * The table <code>pg_catalog.pg_shadow</code>.
     */
    public static final PgShadow PG_SHADOW = Jooq.pg_catalog.tables.PgShadow.PG_SHADOW;

    /**
     * The table <code>pg_catalog.pg_shdepend</code>.
     */
    public static final PgShdepend PG_SHDEPEND = Jooq.pg_catalog.tables.PgShdepend.PG_SHDEPEND;

    /**
     * The table <code>pg_catalog.pg_shdescription</code>.
     */
    public static final PgShdescription PG_SHDESCRIPTION = Jooq.pg_catalog.tables.PgShdescription.PG_SHDESCRIPTION;

    /**
     * The table <code>pg_catalog.pg_shseclabel</code>.
     */
    public static final PgShseclabel PG_SHSECLABEL = Jooq.pg_catalog.tables.PgShseclabel.PG_SHSECLABEL;

    /**
     * The table <code>pg_catalog.pg_stat_activity</code>.
     */
    public static final PgStatActivity PG_STAT_ACTIVITY = Jooq.pg_catalog.tables.PgStatActivity.PG_STAT_ACTIVITY;

    /**
     * The table <code>pg_catalog.pg_stat_all_indexes</code>.
     */
    public static final PgStatAllIndexes PG_STAT_ALL_INDEXES = Jooq.pg_catalog.tables.PgStatAllIndexes.PG_STAT_ALL_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_all_tables</code>.
     */
    public static final PgStatAllTables PG_STAT_ALL_TABLES = Jooq.pg_catalog.tables.PgStatAllTables.PG_STAT_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_archiver</code>.
     */
    public static final PgStatArchiver PG_STAT_ARCHIVER = Jooq.pg_catalog.tables.PgStatArchiver.PG_STAT_ARCHIVER;

    /**
     * The table <code>pg_catalog.pg_stat_bgwriter</code>.
     */
    public static final PgStatBgwriter PG_STAT_BGWRITER = Jooq.pg_catalog.tables.PgStatBgwriter.PG_STAT_BGWRITER;

    /**
     * The table <code>pg_catalog.pg_stat_database</code>.
     */
    public static final PgStatDatabase PG_STAT_DATABASE = Jooq.pg_catalog.tables.PgStatDatabase.PG_STAT_DATABASE;

    /**
     * The table <code>pg_catalog.pg_stat_database_conflicts</code>.
     */
    public static final PgStatDatabaseConflicts PG_STAT_DATABASE_CONFLICTS = Jooq.pg_catalog.tables.PgStatDatabaseConflicts.PG_STAT_DATABASE_CONFLICTS;

    /**
     * The table <code>pg_catalog.pg_stat_gssapi</code>.
     */
    public static final PgStatGssapi PG_STAT_GSSAPI = Jooq.pg_catalog.tables.PgStatGssapi.PG_STAT_GSSAPI;

    /**
     * The table <code>pg_catalog.pg_stat_progress_cluster</code>.
     */
    public static final PgStatProgressCluster PG_STAT_PROGRESS_CLUSTER = Jooq.pg_catalog.tables.PgStatProgressCluster.PG_STAT_PROGRESS_CLUSTER;

    /**
     * The table <code>pg_catalog.pg_stat_progress_create_index</code>.
     */
    public static final PgStatProgressCreateIndex PG_STAT_PROGRESS_CREATE_INDEX = Jooq.pg_catalog.tables.PgStatProgressCreateIndex.PG_STAT_PROGRESS_CREATE_INDEX;

    /**
     * The table <code>pg_catalog.pg_stat_progress_vacuum</code>.
     */
    public static final PgStatProgressVacuum PG_STAT_PROGRESS_VACUUM = Jooq.pg_catalog.tables.PgStatProgressVacuum.PG_STAT_PROGRESS_VACUUM;

    /**
     * The table <code>pg_catalog.pg_stat_replication</code>.
     */
    public static final PgStatReplication PG_STAT_REPLICATION = Jooq.pg_catalog.tables.PgStatReplication.PG_STAT_REPLICATION;

    /**
     * The table <code>pg_catalog.pg_stat_ssl</code>.
     */
    public static final PgStatSsl PG_STAT_SSL = Jooq.pg_catalog.tables.PgStatSsl.PG_STAT_SSL;

    /**
     * The table <code>pg_catalog.pg_stat_subscription</code>.
     */
    public static final PgStatSubscription PG_STAT_SUBSCRIPTION = Jooq.pg_catalog.tables.PgStatSubscription.PG_STAT_SUBSCRIPTION;

    /**
     * The table <code>pg_catalog.pg_stat_sys_indexes</code>.
     */
    public static final PgStatSysIndexes PG_STAT_SYS_INDEXES = Jooq.pg_catalog.tables.PgStatSysIndexes.PG_STAT_SYS_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_sys_tables</code>.
     */
    public static final PgStatSysTables PG_STAT_SYS_TABLES = Jooq.pg_catalog.tables.PgStatSysTables.PG_STAT_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_user_functions</code>.
     */
    public static final PgStatUserFunctions PG_STAT_USER_FUNCTIONS = Jooq.pg_catalog.tables.PgStatUserFunctions.PG_STAT_USER_FUNCTIONS;

    /**
     * The table <code>pg_catalog.pg_stat_user_indexes</code>.
     */
    public static final PgStatUserIndexes PG_STAT_USER_INDEXES = Jooq.pg_catalog.tables.PgStatUserIndexes.PG_STAT_USER_INDEXES;

    /**
     * The table <code>pg_catalog.pg_stat_user_tables</code>.
     */
    public static final PgStatUserTables PG_STAT_USER_TABLES = Jooq.pg_catalog.tables.PgStatUserTables.PG_STAT_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_wal_receiver</code>.
     */
    public static final PgStatWalReceiver PG_STAT_WAL_RECEIVER = Jooq.pg_catalog.tables.PgStatWalReceiver.PG_STAT_WAL_RECEIVER;

    /**
     * The table <code>pg_catalog.pg_stat_xact_all_tables</code>.
     */
    public static final PgStatXactAllTables PG_STAT_XACT_ALL_TABLES = Jooq.pg_catalog.tables.PgStatXactAllTables.PG_STAT_XACT_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_xact_sys_tables</code>.
     */
    public static final PgStatXactSysTables PG_STAT_XACT_SYS_TABLES = Jooq.pg_catalog.tables.PgStatXactSysTables.PG_STAT_XACT_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_stat_xact_user_functions</code>.
     */
    public static final PgStatXactUserFunctions PG_STAT_XACT_USER_FUNCTIONS = Jooq.pg_catalog.tables.PgStatXactUserFunctions.PG_STAT_XACT_USER_FUNCTIONS;

    /**
     * The table <code>pg_catalog.pg_stat_xact_user_tables</code>.
     */
    public static final PgStatXactUserTables PG_STAT_XACT_USER_TABLES = Jooq.pg_catalog.tables.PgStatXactUserTables.PG_STAT_XACT_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_all_indexes</code>.
     */
    public static final PgStatioAllIndexes PG_STATIO_ALL_INDEXES = Jooq.pg_catalog.tables.PgStatioAllIndexes.PG_STATIO_ALL_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_all_sequences</code>.
     */
    public static final PgStatioAllSequences PG_STATIO_ALL_SEQUENCES = Jooq.pg_catalog.tables.PgStatioAllSequences.PG_STATIO_ALL_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_all_tables</code>.
     */
    public static final PgStatioAllTables PG_STATIO_ALL_TABLES = Jooq.pg_catalog.tables.PgStatioAllTables.PG_STATIO_ALL_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_indexes</code>.
     */
    public static final PgStatioSysIndexes PG_STATIO_SYS_INDEXES = Jooq.pg_catalog.tables.PgStatioSysIndexes.PG_STATIO_SYS_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_sequences</code>.
     */
    public static final PgStatioSysSequences PG_STATIO_SYS_SEQUENCES = Jooq.pg_catalog.tables.PgStatioSysSequences.PG_STATIO_SYS_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_sys_tables</code>.
     */
    public static final PgStatioSysTables PG_STATIO_SYS_TABLES = Jooq.pg_catalog.tables.PgStatioSysTables.PG_STATIO_SYS_TABLES;

    /**
     * The table <code>pg_catalog.pg_statio_user_indexes</code>.
     */
    public static final PgStatioUserIndexes PG_STATIO_USER_INDEXES = Jooq.pg_catalog.tables.PgStatioUserIndexes.PG_STATIO_USER_INDEXES;

    /**
     * The table <code>pg_catalog.pg_statio_user_sequences</code>.
     */
    public static final PgStatioUserSequences PG_STATIO_USER_SEQUENCES = Jooq.pg_catalog.tables.PgStatioUserSequences.PG_STATIO_USER_SEQUENCES;

    /**
     * The table <code>pg_catalog.pg_statio_user_tables</code>.
     */
    public static final PgStatioUserTables PG_STATIO_USER_TABLES = Jooq.pg_catalog.tables.PgStatioUserTables.PG_STATIO_USER_TABLES;

    /**
     * The table <code>pg_catalog.pg_statistic</code>.
     */
    public static final PgStatistic PG_STATISTIC = Jooq.pg_catalog.tables.PgStatistic.PG_STATISTIC;

    /**
     * The table <code>pg_catalog.pg_statistic_ext</code>.
     */
    public static final PgStatisticExt PG_STATISTIC_EXT = Jooq.pg_catalog.tables.PgStatisticExt.PG_STATISTIC_EXT;

    /**
     * The table <code>pg_catalog.pg_statistic_ext_data</code>.
     */
    public static final PgStatisticExtData PG_STATISTIC_EXT_DATA = Jooq.pg_catalog.tables.PgStatisticExtData.PG_STATISTIC_EXT_DATA;

    /**
     * The table <code>pg_catalog.pg_stats</code>.
     */
    public static final PgStats PG_STATS = Jooq.pg_catalog.tables.PgStats.PG_STATS;

    /**
     * The table <code>pg_catalog.pg_stats_ext</code>.
     */
    public static final PgStatsExt PG_STATS_EXT = Jooq.pg_catalog.tables.PgStatsExt.PG_STATS_EXT;

    /**
     * The table <code>pg_catalog.pg_subscription</code>.
     */
    public static final PgSubscription PG_SUBSCRIPTION = Jooq.pg_catalog.tables.PgSubscription.PG_SUBSCRIPTION;

    /**
     * The table <code>pg_catalog.pg_subscription_rel</code>.
     */
    public static final PgSubscriptionRel PG_SUBSCRIPTION_REL = Jooq.pg_catalog.tables.PgSubscriptionRel.PG_SUBSCRIPTION_REL;

    /**
     * The table <code>pg_catalog.pg_tables</code>.
     */
    public static final PgTables PG_TABLES = Jooq.pg_catalog.tables.PgTables.PG_TABLES;

    /**
     * The table <code>pg_catalog.pg_tablespace</code>.
     */
    public static final PgTablespace PG_TABLESPACE = Jooq.pg_catalog.tables.PgTablespace.PG_TABLESPACE;

    /**
     * The table <code>pg_catalog.pg_timezone_abbrevs</code>.
     */
    public static final PgTimezoneAbbrevs PG_TIMEZONE_ABBREVS = Jooq.pg_catalog.tables.PgTimezoneAbbrevs.PG_TIMEZONE_ABBREVS;

    /**
     * The table <code>pg_catalog.pg_timezone_names</code>.
     */
    public static final PgTimezoneNames PG_TIMEZONE_NAMES = Jooq.pg_catalog.tables.PgTimezoneNames.PG_TIMEZONE_NAMES;

    /**
     * The table <code>pg_catalog.pg_transform</code>.
     */
    public static final PgTransform PG_TRANSFORM = Jooq.pg_catalog.tables.PgTransform.PG_TRANSFORM;

    /**
     * The table <code>pg_catalog.pg_trigger</code>.
     */
    public static final PgTrigger PG_TRIGGER = Jooq.pg_catalog.tables.PgTrigger.PG_TRIGGER;

    /**
     * The table <code>pg_catalog.pg_ts_config</code>.
     */
    public static final PgTsConfig PG_TS_CONFIG = Jooq.pg_catalog.tables.PgTsConfig.PG_TS_CONFIG;

    /**
     * The table <code>pg_catalog.pg_ts_config_map</code>.
     */
    public static final PgTsConfigMap PG_TS_CONFIG_MAP = Jooq.pg_catalog.tables.PgTsConfigMap.PG_TS_CONFIG_MAP;

    /**
     * The table <code>pg_catalog.pg_ts_dict</code>.
     */
    public static final PgTsDict PG_TS_DICT = Jooq.pg_catalog.tables.PgTsDict.PG_TS_DICT;

    /**
     * The table <code>pg_catalog.pg_ts_parser</code>.
     */
    public static final PgTsParser PG_TS_PARSER = Jooq.pg_catalog.tables.PgTsParser.PG_TS_PARSER;

    /**
     * The table <code>pg_catalog.pg_ts_template</code>.
     */
    public static final PgTsTemplate PG_TS_TEMPLATE = Jooq.pg_catalog.tables.PgTsTemplate.PG_TS_TEMPLATE;

    /**
     * The table <code>pg_catalog.pg_type</code>.
     */
    public static final PgType PG_TYPE = Jooq.pg_catalog.tables.PgType.PG_TYPE;

    /**
     * The table <code>pg_catalog.pg_user</code>.
     */
    public static final PgUser PG_USER = Jooq.pg_catalog.tables.PgUser.PG_USER;

    /**
     * The table <code>pg_catalog.pg_user_mapping</code>.
     */
    public static final PgUserMapping PG_USER_MAPPING = Jooq.pg_catalog.tables.PgUserMapping.PG_USER_MAPPING;

    /**
     * The table <code>pg_catalog.pg_user_mappings</code>.
     */
    public static final PgUserMappings PG_USER_MAPPINGS = Jooq.pg_catalog.tables.PgUserMappings.PG_USER_MAPPINGS;

    /**
     * The table <code>pg_catalog.pg_views</code>.
     */
    public static final PgViews PG_VIEWS = Jooq.pg_catalog.tables.PgViews.PG_VIEWS;
}
