/**
 * This class is generated by jOOQ
 */
package Jooq.public_;


import Jooq.public_.tables.Employee;
import Jooq.public_.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.EMPLOYEE</code>.
     */
    public static final Employee EMPLOYEE = Jooq.public_.tables.Employee.EMPLOYEE;

    /**
     * The table <code>public.User</code>.
     */
    public static final User USER = Jooq.public_.tables.User.USER;
}
