/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables;


import Jooq.pg_catalog.PgCatalog;
import Jooq.pg_catalog.tables.records.PgStatProgressClusterRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatProgressCluster extends TableImpl<PgStatProgressClusterRecord> {

    private static final long serialVersionUID = -1393454172;

    /**
     * The reference instance of <code>pg_catalog.pg_stat_progress_cluster</code>
     */
    public static final PgStatProgressCluster PG_STAT_PROGRESS_CLUSTER = new PgStatProgressCluster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgStatProgressClusterRecord> getRecordType() {
        return PgStatProgressClusterRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.pid</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Integer> PID = createField("pid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.datid</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> DATID = createField("datid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.datname</code>.
     */
    public final TableField<PgStatProgressClusterRecord, String> DATNAME = createField("datname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.relid</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> RELID = createField("relid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.command</code>.
     */
    public final TableField<PgStatProgressClusterRecord, String> COMMAND = createField("command", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.phase</code>.
     */
    public final TableField<PgStatProgressClusterRecord, String> PHASE = createField("phase", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.cluster_index_relid</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> CLUSTER_INDEX_RELID = createField("cluster_index_relid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_scanned</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> HEAP_TUPLES_SCANNED = createField("heap_tuples_scanned", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.heap_tuples_written</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> HEAP_TUPLES_WRITTEN = createField("heap_tuples_written", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.heap_blks_total</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> HEAP_BLKS_TOTAL = createField("heap_blks_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.heap_blks_scanned</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> HEAP_BLKS_SCANNED = createField("heap_blks_scanned", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_cluster.index_rebuild_count</code>.
     */
    public final TableField<PgStatProgressClusterRecord, Long> INDEX_REBUILD_COUNT = createField("index_rebuild_count", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>pg_catalog.pg_stat_progress_cluster</code> table reference
     */
    public PgStatProgressCluster() {
        this("pg_stat_progress_cluster", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_stat_progress_cluster</code> table reference
     */
    public PgStatProgressCluster(String alias) {
        this(alias, PG_STAT_PROGRESS_CLUSTER);
    }

    private PgStatProgressCluster(String alias, Table<PgStatProgressClusterRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgStatProgressCluster(String alias, Table<PgStatProgressClusterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressCluster as(String alias) {
        return new PgStatProgressCluster(alias, this);
    }

    /**
     * Rename this table
     */
    public PgStatProgressCluster rename(String name) {
        return new PgStatProgressCluster(name, null);
    }
}
