/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables;


import Jooq.pg_catalog.PgCatalog;
import Jooq.pg_catalog.tables.records.PgStatisticExtDataRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatisticExtData extends TableImpl<PgStatisticExtDataRecord> {

    private static final long serialVersionUID = 1065938901;

    /**
     * The reference instance of <code>pg_catalog.pg_statistic_ext_data</code>
     */
    public static final PgStatisticExtData PG_STATISTIC_EXT_DATA = new PgStatisticExtData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgStatisticExtDataRecord> getRecordType() {
        return PgStatisticExtDataRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_statistic_ext_data.stxoid</code>.
     */
    public final TableField<PgStatisticExtDataRecord, Long> STXOID = createField("stxoid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext_data.stxdndistinct</code>.
     */
    public final TableField<PgStatisticExtDataRecord, Object> STXDNDISTINCT = createField("stxdndistinct", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_ndistinct"), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext_data.stxddependencies</code>.
     */
    public final TableField<PgStatisticExtDataRecord, Object> STXDDEPENDENCIES = createField("stxddependencies", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_dependencies"), this, "");

    /**
     * The column <code>pg_catalog.pg_statistic_ext_data.stxdmcv</code>.
     */
    public final TableField<PgStatisticExtDataRecord, Object> STXDMCV = createField("stxdmcv", org.jooq.impl.DefaultDataType.getDefaultDataType("pg_mcv_list"), this, "");

    /**
     * Create a <code>pg_catalog.pg_statistic_ext_data</code> table reference
     */
    public PgStatisticExtData() {
        this("pg_statistic_ext_data", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_statistic_ext_data</code> table reference
     */
    public PgStatisticExtData(String alias) {
        this(alias, PG_STATISTIC_EXT_DATA);
    }

    private PgStatisticExtData(String alias, Table<PgStatisticExtDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgStatisticExtData(String alias, Table<PgStatisticExtDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatisticExtData as(String alias) {
        return new PgStatisticExtData(alias, this);
    }

    /**
     * Rename this table
     */
    public PgStatisticExtData rename(String name) {
        return new PgStatisticExtData(name, null);
    }
}
