/**
 * This class is generated by jOOQ
 */
package Jooq.pg_catalog.tables;


import Jooq.pg_catalog.PgCatalog;
import Jooq.pg_catalog.tables.records.PgStatProgressCreateIndexRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatProgressCreateIndex extends TableImpl<PgStatProgressCreateIndexRecord> {

    private static final long serialVersionUID = 476311968;

    /**
     * The reference instance of <code>pg_catalog.pg_stat_progress_create_index</code>
     */
    public static final PgStatProgressCreateIndex PG_STAT_PROGRESS_CREATE_INDEX = new PgStatProgressCreateIndex();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgStatProgressCreateIndexRecord> getRecordType() {
        return PgStatProgressCreateIndexRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.pid</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Integer> PID = createField("pid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.datid</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> DATID = createField("datid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.datname</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, String> DATNAME = createField("datname", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.relid</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> RELID = createField("relid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.index_relid</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> INDEX_RELID = createField("index_relid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.command</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, String> COMMAND = createField("command", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.phase</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, String> PHASE = createField("phase", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.lockers_total</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> LOCKERS_TOTAL = createField("lockers_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.lockers_done</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> LOCKERS_DONE = createField("lockers_done", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.current_locker_pid</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> CURRENT_LOCKER_PID = createField("current_locker_pid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.blocks_total</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> BLOCKS_TOTAL = createField("blocks_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.blocks_done</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> BLOCKS_DONE = createField("blocks_done", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.tuples_total</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> TUPLES_TOTAL = createField("tuples_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.tuples_done</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> TUPLES_DONE = createField("tuples_done", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.partitions_total</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> PARTITIONS_TOTAL = createField("partitions_total", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_stat_progress_create_index.partitions_done</code>.
     */
    public final TableField<PgStatProgressCreateIndexRecord, Long> PARTITIONS_DONE = createField("partitions_done", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>pg_catalog.pg_stat_progress_create_index</code> table reference
     */
    public PgStatProgressCreateIndex() {
        this("pg_stat_progress_create_index", null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_stat_progress_create_index</code> table reference
     */
    public PgStatProgressCreateIndex(String alias) {
        this(alias, PG_STAT_PROGRESS_CREATE_INDEX);
    }

    private PgStatProgressCreateIndex(String alias, Table<PgStatProgressCreateIndexRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgStatProgressCreateIndex(String alias, Table<PgStatProgressCreateIndexRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PgStatProgressCreateIndex as(String alias) {
        return new PgStatProgressCreateIndex(alias, this);
    }

    /**
     * Rename this table
     */
    public PgStatProgressCreateIndex rename(String name) {
        return new PgStatProgressCreateIndex(name, null);
    }
}
